<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Localization\en-US\Mods.LaziestNPC.NPCs.hjson" />
	</ItemGroup>

	<!-- References -->

</Project>